name: umbrella_mesh
channels:
  - conda-forge
dependencies:
  - pip
  - pip:
    - flake8
    - wheel
    - jupyterlab==3.3.4
    - ipykernel==5.5.5
    - jupyterlab-widgets==1.1.1
    - ipywidgets==7.7.2
  - igl
  - matplotlib
  - pytest
  - pytest-html
  - pytest-timeout
